spring:
  application:
    name: salary-service
  zipkin:
    base-url: ${ZIPKIN_URI:http://zipkin:9411/}
server:
  port: 9004


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_SERVER_URI:http://service-registry:8761/eureka/}
  instance:
    preferIpAddress: true
    hostname: service-registry