spring:
  application:
    name: salary-service
  zipkin:
    base-url: ${ZIPKIN_URI:http://zipkin:9411/}
    enabled: false
  kafka:
    consumer:
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9004


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_SERVER_URI:http://service-registry:8761/eureka/}
  instance:
    preferIpAddress: true
    hostname: service-registry

salary:
  topics:
    string-message: salary-message
    long-string-message: salary-long-message
    partitioned-topic-name:
    person-to-salary-topic-name: salary_to_person
    salary-to-person-topic-name: person_to_salary
    avro-person-topic-name: person-to-salary-avro