
server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/people/**
          filters:
            - name: CircuitBreaker
              args:
                name: person-service
                fallbackuri: forward:/personServiceFallBack
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackuri: forward:/departmentServiceFallBack
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: task-service
                fallbackuri: forward:/taskServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 4000

management:
  metrics:
    tags:
      application: MonitoringMicroservices
  endpoints:
    health:
      show-detail: always
    web:
      exposure:
        include: hystrix.stream #, prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry

