version: '3.8'
services:
  config-server:
    image: cevheri/config-server
    container_name: config-server
    hostname: config-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    ports:
    - 9296:9296
