spring:
  application:
    name: task-service
  zipkin:
    base-url: http://zipkin:9411/

server:
  port: 9003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry