version: '3.8'
services:
  department-service:
    image: cevheri/department-service
    container_name: department-service
    hostname: department-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - APP_SLEEP=10 # for zipkin
    ports:
      - 9001:9001
#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#    - 9411:9411
