version: '3.8'
services:
  service-registry:
    image: cevheri/service-registry
    hostname: service-registry
    container_name: service-registry
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - APP_SLEEP=10
    ports:
      - 8761:8761