# syntax=docker/dockerfile:1

#deprecated
# FROM openjdk:11-jdk
WORKDIR /app
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8761


# mvn compile jib:dockerBuild
# docker build -t cevher/ms-service-registry .
# docker run -p 8761:8761 cevher/microservices-service-registry
